language: java
jdk:
- oraclejdk8
after_success:
- bash <(curl -s https://codecov.io/bash)
addons:
  sonarqube:
    token:
      secure: ZuTeIYWzBhyMxxUgNtFwh67fiqJsKBbPX3ZWT2Bo85H4OD+SI75DJJfklXENV6l8G5yBeVoTGUPuPXtGKZxEVraUC1m/G+4JqR0T7OLjAlkOQH6MvaJEf7Q6gFoHJabco/cV4ft6rtQlRnEMIoX/zmDRg6L4GXkdxMY64+hnq06UJXjn4/080owwzSJ1dsPYRVclNIaQuNcpf4ZEIGpc068D0yk+o4jYbTOHepqwaZAVHqiPT6g6kT1tgTthsv6KPz5tefs/+PiuPEEP1H0cfq+UrQSibLyqjJoN2eOTde4yX7o0uDB1B3hBmREL7lX/zMvJ6W091Sk1OrmagDNw6F3MLhCdffqMvsQXWvAE1JBE8E5QDiy3E0sQ6WW/JbPX8axTAEKTY4Lkh77OLBjLiZSvNGAi6L5H2ch11srzrH1OkN5+HJiSqg9qLwOP/wJrVcVCjzoAJJD2fi01PTyQg8U8sgs9VQQ+Sw/80PC3NL876YXkXS354IsiP4J1ZS7ORefS1X92Dc3fxVZCpgbQAF/WQq1SuNKpBYiuZagCpqvD4EMKUyQB0sZQBvrhWoJHDBYM1RcE00tsIY9lNx0sr3CnFiDAkEB77Izm2i40+DKrFzh6CRVk4Z35f7JD1ywzxfijIcyVN9+r7o+B7V79uxDJWJ7gMvNz8NGByGbdv4g=

script:
- sonar-scanner -X

cache:
  directories:
  - "$HOME/.sonar/cache"
