language: java
jdk:
- oraclejdk8
after_success:
- bash <(curl -s https://codecov.io/bash)

addons:
  sonarqube:
    token:
      secure: "IGP3gny/l6Uj1gVaGLVUOfLCXdKhPmgYZtsWmHwcI9Qp6lJWOzoVwX8uXrDyOldt41NtZbUxHAGZchjbRztENWADY8MctyjYlmKEbWdwvnc/Le3DH9nO+2rHgy+RxlFE8zu5GNNepus2TZYA6Zmy+cm2plcfy/q4FNpjps9iTNTXs/yGqBXFFpAAmB5THKApLqa9nD8aC5ELpwdBly6ExWpultdAdSUqBivMtayfBYRui4sSeb66MjVcBobBe9InluCIYViMw34nq8v+Qlry2uBjl5fIooZVKEVQa5pBJvxhn2vPpBARk3tKeCbeMG8EuhcuuXUVFGeU2cflQ7bOFGzUpJs/CXy2PkJSl6FRkzroWZYb/xFfg9Ru680iXJP/tmwGYXf/YV7/9cyp2JMqOz8UON0QsxtWgQi7Y3RQg+9byzoBbwnYVPP/9nNgoDo5ZtOwTGUyABG3/eq/D2KrdpJ+kicX7W+DjKa0gOOuAg5T3T97VfP2HagYmdAGjGSAkh3N0k0h7oR5gGjRAB26EhLCvvLvdrJ+V0vLciT60GFry0YwXjdGAVTW6KmeeTXCWXrpViedWGVwEj6UBXhFBGhTfk+c2MYcvZFTeVlzq7MxAuqNlWsTArx5DAjJKIFiyc3kLh6D+yBaXPOQX0QHXNsSlUxfonh/QmScoUvzmzE="

script:
- sonar-scanner -X

cache:
  directories:
  - "$HOME/.sonar/cache"

#      secure: FP7bpr2ZYD2fK1gch8A3NunqKISDX70yE1G7Qr8rJERihQNAj7xYlEEdwx2ZV69FLJzTJnDSaYCl1KDr+jzGZ1GOubxu2UL6f5oAwbVUPGzzax1LZp/3jawhvYga9GU2BvJhbM4NFJF3IlHEtJYFegZjr31E4v9h6DAL3CTr6ulB0DaRdiSSEy17CmNoQMKayuORWU5A04UfLVEYXLiCWqSSc23pewSC3ysbn8faSBIugL09kRvDOT0NEnRjh0Z5BlGTdB0ieQ08akt7sB14nXlRkTUdtOPggPzbQFOP7InA2aUt8equKJedwe/b0hrn7y4jEcGQPUsZlCg46ljXFFC9qHOefBiJhZglzpWN9h5je+2jd//PTScAZ8T4Q4BsjpEJrB7QQwzpngVkNAH8/yh3g3sBhl7Q+sWAGioU57XCz1yZq+pTwZcItffwXOftTEZeQdFeD/iFpMfpfa9b1OwBPjD19SiHWbbP4yIVN7bHNosZ0t35hYd8UJliZBXWt25WgB/BI74CYgU7ACEEhodbYfSmHDPIUIHBFCsbR7xvpcBHoPgphUiZiNTjR6WxNnvU1s8CthdvpQVpPFslcUWxmRwNmh22VfJ9Vai5l8n2hESlojMA3e0vPCYrTBJQc1vNzuW8TVBvRDhlLrNmceajy7zvoSVuZKGteqZCLZ4=
#      secure: ZuTeIYWzBhyMxxUgNtFwh67fiqJsKBbPX3ZWT2Bo85H4OD+SI75DJJfklXENV6l8G5yBeVoTGUPuPXtGKZxEVraUC1m/G+4JqR0T7OLjAlkOQH6MvaJEf7Q6gFoHJabco/cV4ft6rtQlRnEMIoX/zmDRg6L4GXkdxMY64+hnq06UJXjn4/080owwzSJ1dsPYRVclNIaQuNcpf4ZEIGpc068D0yk+o4jYbTOHepqwaZAVHqiPT6g6kT1tgTthsv6KPz5tefs/+PiuPEEP1H0cfq+UrQSibLyqjJoN2eOTde4yX7o0uDB1B3hBmREL7lX/zMvJ6W091Sk1OrmagDNw6F3MLhCdffqMvsQXWvAE1JBE8E5QDiy3E0sQ6WW/JbPX8axTAEKTY4Lkh77OLBjLiZSvNGAi6L5H2ch11srzrH1OkN5+HJiSqg9qLwOP/wJrVcVCjzoAJJD2fi01PTyQg8U8sgs9VQQ+Sw/80PC3NL876YXkXS354IsiP4J1ZS7ORefS1X92Dc3fxVZCpgbQAF/WQq1SuNKpBYiuZagCpqvD4EMKUyQB0sZQBvrhWoJHDBYM1RcE00tsIY9lNx0sr3CnFiDAkEB77Izm2i40+DKrFzh6CRVk4Z35f7JD1ywzxfijIcyVN9+r7o+B7V79uxDJWJ7gMvNz8NGByGbdv4g=
  