language: java
jdk:
- oraclejdk8
after_success:
- bash <(curl -s https://codecov.io/bash)
addons:
  sonarqube:
    token: 
      secure: FP7bpr2ZYD2fK1gch8A3NunqKISDX70yE1G7Qr8rJERihQNAj7xYlEEdwx2ZV69FLJzTJnDSaYCl1KDr+jzGZ1GOubxu2UL6f5oAwbVUPGzzax1LZp/3jawhvYga9GU2BvJhbM4NFJF3IlHEtJYFegZjr31E4v9h6DAL3CTr6ulB0DaRdiSSEy17CmNoQMKayuORWU5A04UfLVEYXLiCWqSSc23pewSC3ysbn8faSBIugL09kRvDOT0NEnRjh0Z5BlGTdB0ieQ08akt7sB14nXlRkTUdtOPggPzbQFOP7InA2aUt8equKJedwe/b0hrn7y4jEcGQPUsZlCg46ljXFFC9qHOefBiJhZglzpWN9h5je+2jd//PTScAZ8T4Q4BsjpEJrB7QQwzpngVkNAH8/yh3g3sBhl7Q+sWAGioU57XCz1yZq+pTwZcItffwXOftTEZeQdFeD/iFpMfpfa9b1OwBPjD19SiHWbbP4yIVN7bHNosZ0t35hYd8UJliZBXWt25WgB/BI74CYgU7ACEEhodbYfSmHDPIUIHBFCsbR7xvpcBHoPgphUiZiNTjR6WxNnvU1s8CthdvpQVpPFslcUWxmRwNmh22VfJ9Vai5l8n2hESlojMA3e0vPCYrTBJQc1vNzuW8TVBvRDhlLrNmceajy7zvoSVuZKGteqZCLZ4=
script:
- sonar-scanner -X
cache:
  directories:
  - "$HOME/.sonar/cache"
#env:
#  global:
#    secure: FP7bpr2ZYD2fK1gch8A3NunqKISDX70yE1G7Qr8rJERihQNAj7xYlEEdwx2ZV69FLJzTJnDSaYCl1KDr+jzGZ1GOubxu2UL6f5oAwbVUPGzzax1LZp/3jawhvYga9GU2BvJhbM4NFJF3IlHEtJYFegZjr31E4v9h6DAL3CTr6ulB0DaRdiSSEy17CmNoQMKayuORWU5A04UfLVEYXLiCWqSSc23pewSC3ysbn8faSBIugL09kRvDOT0NEnRjh0Z5BlGTdB0ieQ08akt7sB14nXlRkTUdtOPggPzbQFOP7InA2aUt8equKJedwe/b0hrn7y4jEcGQPUsZlCg46ljXFFC9qHOefBiJhZglzpWN9h5je+2jd//PTScAZ8T4Q4BsjpEJrB7QQwzpngVkNAH8/yh3g3sBhl7Q+sWAGioU57XCz1yZq+pTwZcItffwXOftTEZeQdFeD/iFpMfpfa9b1OwBPjD19SiHWbbP4yIVN7bHNosZ0t35hYd8UJliZBXWt25WgB/BI74CYgU7ACEEhodbYfSmHDPIUIHBFCsbR7xvpcBHoPgphUiZiNTjR6WxNnvU1s8CthdvpQVpPFslcUWxmRwNmh22VfJ9Vai5l8n2hESlojMA3e0vPCYrTBJQc1vNzuW8TVBvRDhlLrNmceajy7zvoSVuZKGteqZCLZ4=
